DROP TABLE USER IF EXISTS CASCADE;
DROP TABLE COMMENT IF EXISTS CASCADE;

CREATE TABLE USER 
(	
	USER_ID VARCHAR(32) PRIMARY KEY,
	USER_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE COMMENT 
(	
	COMMENT_NO INTEGER primary key,
	USER_ID VARCHAR(32) NOT NULL,
	COMMENT_CONTENT VARCHAR(500),
	REG_DATE TIMESTAMP
);
